### ISSUE TITLE
Does not let me enter dialog

### ISSUE THREAD

**Issue by deadpahn** [tari01/caja-rename#7]
PC SPECS:
OS: Debian GNU/Linux 10 (buster) x86_64 
Kernel: 4.19.0-17-amd64 
DE: MATE 
WM: Metacity (Marco) 

Installed via "sudo apt install caja-rename". Tried caja -q multiple times. When I open caja, I'm not able to rename multiple files. I see no option for the dialog box to appear. Right clicking on multiple files will have"rename" greyed out. F2 does not prompt a rename dialog.

Did not try restarting my machine.

**Comment by tari01** [comment]
@deadpahn 

Please install the latest caja-rename from GitHub, then restart caja. The context menu should have a "Rename all..." item when multiple files/folders are selected.

Please also report back here.

**Comment by 9ngol** [comment]
Same thing happens to me. Installed from AUR with "yay -S caja-rename" And caja -q after install. same behaviour as first post.
OS: Arch Linux x86_6
Kernel: 5.15.4-zen1-1-zen
WM: Metacity (Marco) 
DE: MATE 1.26.0

**Comment by tari01** [comment]
@9ngol 

I cannot replicate this on my Arch. There was recently an issue with python-caja (https://github.com/tari01/caja-rename/issues/6), also, if a restart doesn't help, is there anything relevant in ~/.xsession-errors?

**Comment by 9ngol** [comment]
I have no idea what it says but. I cleared .xsession-errors and restarted PC. First message.
`(caja:1036): Gtk-WARNING **: 08:17:51.877: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(mate-power-manager:1169): PowerManager-WARNING **: 08:17:51.979: Failed to get session for pid 1169: The name org.freedesktop.ConsoleKit was not provided by any .service files

(mate-power-manager:1169): PowerManager-WARNING **: 08:17:51.982: could not map keysym 1008ffa8 to keycode

** (mate-screensaver:1166): WARNING **: 08:17:52.011: Screensaver already running in this session

(pamac-tray:1151): Gdk-CRITICAL **: 08:17:52.213: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "/usr/share/caja-python/extensions/caja-rename.py", line 53, in __init__
    self.oPixBufFile = Gtk.IconTheme().get_default().load_icon('gtk-file', 22, 0)
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'gtk-file' not present in theme Zafiro-Icons-Dark-Blue-f (0)
sys:1: Warning: invalid uninstantiatable type '(null)' in cast to 'GObject'
`

**Comment by tari01** [comment]
> > Traceback (most recent call last):
> > File "/usr/share/caja-python/extensions/caja-rename.py", line 53, in **init**
> > self.oPixBufFile = Gtk.IconTheme().get_default().load_icon('gtk-file', 22, 0)
> > gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'gtk-file' not present in theme Zafiro-Icons-Dark-Blue-f (0)
> > sys:1: Warning: invalid uninstantiatable type '(null)' in cast to 'GObject'

Bingo! Your theme is missing gtk-file. I will update the code to use generic named icons and catch the error is the icon is missing.

**Comment by tari01** [comment]
@9ngol 

I have published release 21.11.24 (also in the AUR). It should work for you now. Please test it and close this issue if everithing is OK. Thanks.

**Comment by 9ngol** [comment]
> @9ngol
> 
> I have published release 21.11.24 (also in the AUR). It should work for you now. Please test it and close this issue if everything is OK. Thanks.
Its fixed for me. Thanks.
But i'm not the one who created this issue and i don't have a button to close it.
